# Generated by Django 5.0.2 on 2024-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(verbose_name="주소")),
            ],
            options={
                "verbose_name": "북마크",
                "verbose_name_plural": "북마크 목록",
            },
        ),
    ]
